// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/simulation": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Выполняет симуляцию SIP INVITE, прогоняет его через бизнес-логику Policy (logic) и возвращает INVITE/RESPONSE в сыром и разобранном виде.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "SIP Policy Simulation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "A-number (From)",
                        "name": "a_number",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "B-number (To)",
                        "name": "b_number",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "C-number (Diversion)",
                        "name": "c_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Источник SIP пакета (X-SrcIP)",
                        "name": "src_ip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IP SBC (по умолчанию 0.0.0.0)",
                        "name": "sbc_ip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная симуляция",
                        "schema": {
                            "$ref": "#/definitions/http.InviteDebugResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка обработки URI или другого системного компонента",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.InviteDebugResponse": {
            "description": "Parsed SIP request and response with raw packets",
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "invite": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.SIPHeader"
                            }
                        },
                        "result": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.SIPHeader"
                            }
                        }
                    }
                }
            }
        },
        "http.SIPHeader": {
            "description": "SIP Header pair",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "query"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "25.11.24",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "goMobile",
	Description:      "SIP Simulation and Policy Engine for internal debugging.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
